version: '3'

services: 
    web:
        build: ./web
        expose: 
            - 8000
        volumes: 
            - static_data:/app/webapp/static
    nginx:
        build: ./nginx
        ports:
            - 5001:80
        volumes: 
            - static_data:/app/webapp/static
        depends_on: 
            - web

volumes:
    static_data: